[general]
import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
size = 12
normal.family = "MesloLGS Nerd Font Mono"